## learning-AI101 : vehicle price regression (ML)
### 자동차 데이터를 KNN, multiple regression, SVM, lasso, ridge, decision tree, random forest, XGBoost, gradient boosting, GPR 기법을 적용하여 regression

<br>

- **임규연 (lky473736)**
- 2024.08.12. ~ 2024.08.13.에 문서 작성
- **kaggle** : https://www.kaggle.com/datasets/nehalbirla/vehicle-dataset-from-cardekho
- **data abstract** : This dataset contains information about used cars. This data can be used for a lot of purposes such as price prediction to exemplify the use of linear regression in Machine Learning.

------

----
## <span id='ml'><mark>ML</mark></span>

machine learning으로 vehicle price를 regression한다. 목차는 아래와 같다.

- **1. 데이터 EDA (탐색적 데이터 분석) 및 데이터 전처리**
- **2. 각종 모델을 적용하여 regression 및 각 모델의 score 비교**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

-------

### 1. 데이터 EDA (탐색적 데이터 분석)

regression 진행하기 전, 데이터 구조를 파악하고, 전처리를 진행한다.

- **데이터 구조 파악 및 EDA**
    - 각 feature가 의미하는 바를 분석, 결측치 파악 후 어떻게 classification을 진행하는 것이 탁월할 지 파악
    - 각 feature에 대한 사분위수, mean, max, min, median, corr
    - seaborn을 통한 corr 상관관계 및 histplot 시각화
    - 각 feature에 대한 box plot 시각화
    - target의 도수를 bar plot 시각화
    
- **전처리**
    - train, test, val set으로 split
    - scaling (Z-score normalization)
    - 결측치 확인 및 filling by everage value
    - Polynormial Feature
    
아래와 같은 순서로 진행한다.

- **순서**
    - (1) dataframe으로 파일 열기 및 head, info 파악
    - (2) 각 describe를 통한 편향성 확인 및 기초통계량 확인
    - (3) 각 열마다 unique한 component 목록 확인 및 전처리 여부 판단 후 수행
    - (4) seaborn heatmap로 상관관계 파악
    - (5) seaborn pairplot으로 상관관계 시각화
    - (6) outlier 확인 위해 boxplot 시각화
    - (7) 결측치 확인 및 filling by evarage value
    - (8) input, target set -> train, test, val set으로 split
    - (9) labeling (Label Encoding)
    - (10) scaling (Z-score normalization)

#### (1) dataframe으로 파일 열기 및 head, info 파악

이번 regression은 조금 난해한 길을 가려고 한다. 현재 ./data/vehicle 디렉토리 안에는 아래와 같이 파일이 구성되어 있다.

```sh
alphastation:learning-ai101 alphastation$ ls -lha ./report/data/vehicle
total 3472
drwxr-xr-x   6 alphastation  staff   192B  8 13 00:03 .
drwxr-xr-x  12 alphastation  staff   384B  8 13 00:02 ..
-rw-rw-r--@  1 alphastation  staff   346K  1 14  2023 CAR DETAILS FROM CAR DEKHO.csv
-rw-rw-r--@  1 alphastation  staff   1.0M  1 14  2023 Car details v3.csv
-rw-rw-r--@  1 alphastation  staff    17K  1 14  2023 car data.csv
-rw-rw-r--@  1 alphastation  staff   345K  1 14  2023 car details v4.csv
```
각 파일은 아래와 같다.
- car data.csv : 기본적인 feature만 구성
- Car details v3.csv : 기본적인 feature + 세부적인 범주형 feature
- Car details v4.csv : v3보다 정교해진 data, component 더 많아짐
- CAR DETAILS FROM CAR DEKHO.csv

이 중 가장 feature 수가 많은 Car details v4.csv dataset을 이용하여 regression을 진행해보겠다.

In [7]:
# 파일 열기 및 head, info 파악

df = pd.read_csv('data/vehicle/car details v4.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                2059 non-null   object
 1   Model               2059 non-null   object
 2   Price               2059 non-null   int64
 3   Year                2059 non-null   int64
 4   Kilometer           2059 non-null   int64
 5   Fuel Type           2059 non-null   object
 6   Transmission        2059 non-null   object
 7   Location            2059 non-null   object
 8   Color               2059 non-null   object
 9   Owner               2059 non-null   object
 10  Seller Type         2059 non-null   object
 11  Engine              1979 non-null   object
 12  Max Power           1979 non-null   object
 13  Max Torque          1979 non-null   object
 14  Drivetrain          1923 non-null   object
 15  Length              1995 non-null   float64
 16  Width               1995 non-null   float64
 17  Height              1995 non-null   float64
 18  Seating Capacity    1995 non-null   float64
 19  Fuel Tank Capacity  1946 non-null   float64
dtypes: float64(5), int64(3), object(12)
memory usage: 321.8+ KB

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

#### (2) 각 describe를 통한 편향성 확인 및 기초통계량 확인

In [8]:
# 기초통계량 확인

df.describe()

,Price,Year,Kilometer,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
count,2.059000e+03,2059.000000,2.059000e+03,1995.000000,1995.000000,1995.000000,1995.000000,1946.000000
mean,1.702992e+06,2016.425449,5.422471e+04,4280.860652,1767.991980,1591.735338,5.306266,52.002210
std,2.419881e+06,3.363564,5.736172e+04,442.458507,135.265825,136.073956,0.822170,15.110198
min,4.900000e+04,1988.000000,0.000000e+00,3099.000000,1475.000000,1165.000000,2.000000,15.000000
25%,4.849990e+05,2014.000000,2.900000e+04,3985.000000,1695.000000,1485.000000,5.000000,41.250000
50%,8.250000e+05,2017.000000,5.000000e+04,4370.000000,1770.000000,1545.000000,5.000000,50.000000
75%,1.925000e+06,2019.000000,7.200000e+04,4629.000000,1831.500000,1675.000000,5.000000,60.000000
max,3.500000e+07,2022.000000,2.000000e+06,5569.000000,2220.000000,1995.000000,8.000000,105.000000

위 기초통계량을 보면 아래와 같은 내용을 알 수 있다.

- 가장 오래된 차 연도는 1988, 최신의 차 연도는 2022년이니, 비교적 최신의 dataset임을 알 수 있다.
- 범주형 column은 출력되지 않고, 연속형 column의 기초통계량만 표현하고 있다.
- **가격 측면**
  - 가격의 표준편차는 약 2,419,881달러로, 가격 변동성이 크다.
  - 가격의 최소값은 49,000달러, 최대값은 35,000,000달러이다.
- **주행 거리 측면**
  - 주행 거리의 표준편차는 약 57,361킬로미터로, 주행 거리의 차이가 크다.
  - 최소 주행 거리는 0킬로미터, 최대 주행 거리는 2,000,000킬로미터이다. 아예 타지 않은 차도 있다는 뜻이다.
- **연료 탱크 용량 측면**
  - 최소 연료 탱크 용량은 15리터, 최대 용량은 105리터이다.

#### (3) 각 열마다 unique한 component 목록 확인 및 전처리 여부 판단 후 수행

In [16]:
# 각 열마다의 component를 출력

'''
#   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Make                2059 non-null   object 
 1   Model               2059 non-null   object 
 2   Price               2059 non-null   int64  
 3   Year                2059 non-null   int64  
 4   Kilometer           2059 non-null   int64  
 5   Fuel Type           2059 non-null   object 
 6   Transmission        2059 non-null   object 
 7   Location            2059 non-null   object 
 8   Color               2059 non-null   object 
 9   Owner               2059 non-null   object 
 10  Seller Type         2059 non-null   object 
 11  Engine              1979 non-null   object 
 12  Max Power           1979 non-null   object 
 13  Max Torque          1979 non-null   object 
 14  Drivetrain          1923 non-null   object 
 15  Length              1995 non-null   float64
 16  Width               1995 non-null   float64
 17  Height              1995 non-null   float64
 18  Seating Capacity    1995 non-null   float64
 19  Fuel Tank Capacity  1946 non-null   float64
'''

for col_name in [feature for feature in df.columns if df[feature].dtype == 'object'] :
    print (f'col_name : {col_name} \ncompo : {df[col_name].unique()}')
    print ()

col_name : Make
compo : ['Honda' 'Maruti Suzuki' 'Hyundai' 'Toyota' 'Mercedes-Benz' 'BMW' 'Skoda'
 'Nissan' 'Renault' 'Tata' 'Volkswagen' 'Ford' 'Audi' 'Mahindra' 'MG'
 'Jeep' 'Porsche' 'Kia' 'Land Rover' 'Volvo' 'Maserati' 'Jaguar' 'Isuzu'
 'Fiat' 'MINI' 'Ferrari' 'Mitsubishi' 'Datsun' 'Lamborghini' 'Chevrolet'
 'Ssangyong' 'Rolls-Royce' 'Lexus']

col_name : Model
compo : ['Amaze 1.2 VX i-VTEC' 'Swift DZire VDI' 'i10 Magna 1.2 Kappa2' ...
 'Ritz Vxi (ABS) BS-IV' 'XUV500 W8 [2015-2017]'
 'Figo Duratec Petrol ZXI 1.2']

col_name : Fuel Type
compo : ['Petrol' 'Diesel' 'CNG' 'LPG' 'Electric' 'CNG + CNG' 'Hybrid'
 'Petrol + CNG' 'Petrol + LPG']

col_name : Transmission
compo : ['Manual' 'Automatic']

col_name : Location
compo : ['Pune' 'Ludhiana' 'Lucknow' 'Mangalore' 'Mumbai' 'Coimbatore' 'Bangalore'
 'Delhi' 'Raipur' 'Kanpur' 'Patna' 'Vadodara' 'Hyderabad' 'Yamunanagar'
 'Gurgaon' 'Jaipur' 'Deoghar' 'Agra' 'Goa' 'Warangal' 'Jalandhar' 'Noida'
 'Ahmedabad' 'Mohali' 'Navi Mumbai' 'Ghaziabad' 'Kolkata' 'Zirakpur'
 'Nagpur' 'Thane' 'Faridabad' 'Ranchi' 'Chandigarh' 'Amritsar' 'Chennai'
 'Udupi' 'Panvel' 'Jamshedpur' 'Aurangabad' 'Rudrapur' 'Nashik' 'Varanasi'
 'Salem' 'Dehradun' 'Valsad' 'Haldwani' 'Dharwad' 'Surat' 'Indore'
 'Karnal' 'Panchkula' 'Mysore' 'Rohtak' 'Ambala Cantt' 'Samastipur'
 'Unnao' 'Purnea' 'Bhubaneswar' 'Kheda' 'Kollam' 'Meerut' 'Ernakulam'
 'Kharar' 'Mirzapur' 'Bhopal' 'Gorakhpur' 'Guwahati' 'Allahabad'
 'Muzaffurpur' 'Faizabad' 'Kota' 'Pimpri-Chinchwad' 'Dak. Kannada'
 'Ranga Reddy' 'Bulandshahar' 'Roorkee' 'Siliguri']

col_name : Color
compo : ['Grey' 'White' 'Maroon' 'Red' 'Blue' 'Orange' 'Silver' 'Brown' 'Black'
 'Bronze' 'Gold' 'Beige' 'Green' 'Yellow' 'Purple' 'Others' 'Pink']

col_name : Owner
compo : ['First' 'Second' 'Third' 'Fourth' 'UnRegistered Car' '4 or More']

col_name : Seller Type
compo : ['Corporate' 'Individual' 'Commercial Registration']

col_name : Engine
compo : ['1198 cc' '1248 cc' '1197 cc' '2393 cc' '1373 cc' '1991 cc' '1995 cc'
 '1798 cc' '1461 cc' '999 cc' '1462 cc' '1956 cc' '998 cc' '796 cc'
 '1591 cc' '1086 cc' '1199 cc' '1582 cc' nan '1047 cc' '2143 cc' '1968 cc'
 '1796 cc' '2498 cc' '2494 cc' '2179 cc' '1998 cc' '1497 cc' '1196 cc'
 '2755 cc' '1799 cc' '1493 cc' '1399 cc' '1498 cc' '1997 cc' '1598 cc'
 '2993 cc' '2995 cc' '2982 cc' '1353 cc' '1984 cc' '2967 cc' '2609 cc'
 '1950 cc' '1999 cc' '4663 cc' '1451 cc' '2354 cc' '1396 cc' '2987 cc'
 '2997 cc' '1336 cc' '4163 cc' '3496 cc' '799 cc' '2979 cc' '4806 cc'
 '2996 cc' '1061 cc' '2184 cc' '2497 cc' '2999 cc' '1948 cc' '3436 cc'
 '2925 cc' '2489 cc' '1368 cc' '1797 cc' '1298 cc' '2694 cc' '1186 cc'
 '1364 cc' '3498 cc' '3982 cc' '1120 cc' '2523 cc' '1988 cc' '3902 cc'
 '624 cc' '2477 cc' '3198 cc' '5204 cc' '814 cc' '2953 cc' '1496 cc'
 '1499 cc' '1996 cc' '5461 cc' '1395 cc' '2835 cc' '2148 cc' '2696 cc'
 '1794 cc' '1969 cc' '6592 cc' '2199 cc' '4951 cc' '1495 cc' '2487 cc'
 '2998 cc' '2198 cc' '2157 cc' '1595 cc' '1586 cc' '936 cc' '1332 cc'
 '2400 cc' '793 cc' '995 cc']

col_name : Max Power
compo : ['87 bhp @ 6000 rpm' '74 bhp @ 4000 rpm' '79 bhp @ 6000 rpm'
 '82 bhp @ 6000 rpm' '148 bhp @ 3400 rpm' '91 bhp @ 6000 rpm'
 '181 bhp @ 5500 rpm' '188 bhp @ 4000 rpm' '177 bhp @ 5100 rpm'
 '84 bhp @ 3750 rpm' '67 bhp @ 5500 rpm' '103 bhp @ 6000 rpm'
 '138 bhp @ 3750 rpm' '103 bhp @ 5000 rpm' '67 bhp @ 6000 rpm'
 '47 bhp @ 6000 rpm' '122 bhp @ 6400 rpm' '68 bhp @ 5500 rpm'
 '118 bhp @ 6000 rpm' '58 bhp @ 6000 rpm' '85 bhp @ 6000 rpm'
 '89 bhp @ 6000 rpm' '126 bhp @ 4000 rpm' '124 bhp @ 6000 rpm' nan
 '62 bhp @ 5500 rpm' '84 bhp @ 6000 rpm' '69 bhp @ 4000 rpm'
 '168 bhp @ 3000 rpm' '203 bhp @ 4200 rpm' '138 bhp @ 6400 rpm'
 '177 bhp @ 4200 rpm' '165@5500' '105 bhp @ 3800 rpm' '83 bhp @ 6000 rpm'
 '89 bhp @ 4000 rpm' '169 bhp @ 3750 rpm' '101 bhp @ 3600 rpm'
 '190 bhp @ 4000 rpm' '171 bhp @ 3750 rpm' '120 bhp @ 4000 rpm'
 '181 bhp @ 5000 rpm' '117 bhp @ 6600 rpm' '74 bhp @ 4200 rpm'
 '73 bhp @ 6000 rpm' '184 bhp @ 4000 rpm' '174 bhp @ 3400 rpm'
 '130 bhp @ 6300 rpm' '99 bhp @ 4000 rpm' '141 bhp @ 3500 rpm'
 '68 bhp @ 4000 rpm' '74 bhp @ 5400 rpm' '99 bhp @ 3600 rpm'
 '179 bhp @ 6000 rpm' '150 bhp @ 5000 rpm' '207@4200' '184 bhp @ 3500 rpm'
 '103 bhp @ 5250 rpm' '170 bhp @ 4200 rpm' '202 bhp @ 5700 rpm'
 '108 bhp @ 3900 rpm' '58 bhp @ 6200 rpm' '258 bhp @ 4000 rpm'
 '335 bhp @ 5300 rpm' '241 bhp @ 5500 rpm' '121 bhp @ 6300 rpm'
 '177 bhp @ 3750 rpm' '115 bhp @ 3750 rpm' '118@6600' '204 bhp @ 4200 rpm'
 '169 bhp @ 3600 rpm' '104 bhp @ 5250 rpm' '63@5500' '168 bhp @ 3750 rpm'
 '81 bhp @ 6000 rpm' '138 bhp @ 6000 rpm' '188 bhp @ 4200 rpm'
 '245 bhp @ 2910 rpm' '67 bhp @ 6200 rpm' '116@3800' '248 bhp @ 5000 rpm'
 '105 bhp @ 5600 rpm' '190 bhp @ 3800 rpm' '121 bhp @ 3500 rpm'
 '113 bhp @ 4000 rpm' '192 bhp @ 3800 rpm' '177 bhp @ 4000 rpm'
 '201 bhp @ 3800 rpm' '453 bhp @ 5250 rpm' '141 bhp @ 5000 rpm'
 '108 bhp @ 6000 rpm' '152@6000' '105 bhp @ 5250 rpm' '103 bhp @ 4400 rpm'
 '153 bhp @ 3750 rpm' '134 bhp @ 3600 rpm' '68@6200' '99 bhp @ 3750 rpm'
 '241 bhp @ 3800 rpm' '204 bhp @ 3800 rpm' '75@4000' '102@5600'
 '174 bhp @ 4200 rpm' '234@3800' '150 bhp @ 3500 rpm' '186 bhp @ 5600 rpm'
 '231@3800' '254 bhp @ 3600 rpm' '109 bhp @ 5000 rpm' '108 bhp @ 5000 rpm'
 '104 bhp @ 5200 rpm' '444 bhp @ 8250 rpm' '272 bhp @ 6000 rpm'
 '53 bhp @ 5678 rpm' '180 bhp @ 4000 rpm' '140 bhp @ 3750 rpm'
 '172 bhp @ 3400 rpm' '275 bhp @ 4000 rpm' '500 bhp @ 6500 rpm' '171@3600'
 '58 bhp @ 5500 rpm' '362 bhp @ 5500 rpm' '296 bhp @ 5500 rpm' '67@6200'
 '245 bhp @ 4400 rpm' '130 bhp @ 3750 rpm' '148 bhp @ 4000 rpm' '177@4000'
 '174 bhp @ 3600 rpm' '80@5200' '255 bhp @ 3400 rpm' '90@4300' '47@6200'
 '325 bhp @ 7400 rpm' '153 bhp @ 6200 rpm' '282 bhp @ 3600 rpm'
 '89 bhp @ 6200 rpm' '188 bhp @ 3500 rpm' '95@3600' '160 bhp @ 5500 rpm'
 '89 bhp @ 3750 rpm' '248 bhp @ 5200 rpm' '138 bhp @ 4000 rpm'
 '262 bhp @ 4000 rpm' '147 bhp @ 6500 rpm' '87@6000' '90@6000'
 '119 bhp @ 6600 rpm' '164 bhp @ 5200 rpm' '208 bhp @ 4300 rpm'
 '118 bhp @ 5500 rpm' '181 bhp @ 5800 rpm' '68 bhp @ 6000 rpm' '120@4000'
 '136@5600' '67 bhp @ 3800 rpm' '99 bhp @ 5000 rpm' '68 bhp @ 6200 rpm'
 '272 bhp @ 6300 rpm' '114 bhp @ 4000 rpm' '113 bhp @ 6300 rpm'
 '105 bhp @ 4400 rpm' '118 bhp @ 6600 rpm' '70 bhp @ 6250 rpm' '204@6100'
 '463 bhp @ 5250 rpm' '136 bhp @ 3200 rpm' '71 bhp @ 4000 rpm' '59@6200'
 '154 bhp @ 4000 rpm' '112 bhp @' '75 bhp @ 3200 rpm' '295 bhp @ 6500 rpm'
 '120@5500' '241 bhp @ 4200 rpm' '100 bhp @ 3750 rpm' '660 bhp @ 8000 rpm'
 '141 bhp @ 4000 rpm' '190 bhp @ 3500 rpm' '35@5250' '176 bhp @ 4000 rpm'
 '197 bhp @ 3000 rpm' '67 bhp @ 5000 rpm' '114 bhp @ 6300 rpm'
 '602 bhp @ 8250 rpm' '55 bhp @ 5500 rpm' '154 bhp @ 3200 rpm'
 '182 bhp @ 4000 rpm' '80 bhp @ 5600 rpm' '118 bhp @ 3750 rpm'
 '75 bhp @ 6200 rpm' '109 bhp @ 6300 rpm' '326 bhp @ 3600 rpm'
 '116 bhp @ 6600 rpm' '258 bhp @ 3600 rpm' '108 bhp @ 3750 rpm' '122@4000'
 '215 bhp @ 4000 rpm' '100 bhp @ 3600 rpm' '368 bhp @ 6300 rpm'
 '194 bhp @ 5800 rpm' '244 bhp @ 4000 rpm' '108 bhp @ 4000 rpm'
 '148 bhp @ 5000 rpm' '194 bhp @ 5500 rpm' '56@5500' '182 bhp @ 3500 rpm'
 '171 @3600' '128 bhp @ 4000 rpm' '335 bhp @ 5200 rpm'
 '189 bhp @ 5000 rpm' '76 bhp @ 6000 rpm' '255 bhp @ 3600 rpm'
 '157 bhp @ 6500 rpm' '94 bhp @ 6000 rpm' '184 bhp @ 5500 rpm'
 '201 bhp @ 5800 rpm' '289 bhp @ 4000 rpm' '170 bhp @ 3800 rpm'
 '164 bhp @ 3800 rpm' '142@4000' '79 bhp @ 3600 rpm' '87 bhp @ 6300 rpm'
 '94 bhp @ 4000 rpm' '70 bhp @ 3600 rpm' '178 bhp @ 5100 rpm'
 '118 bhp @ 4000 rpm' '90 bhp @ 5600 rpm' '245 bhp @ 4000 rpm' '150@4000'
 '189 bhp @' '170@3700' '231 bhp @ 3000 rpm' '85 bhp @ 3750 rpm'
 '121 bhp @ 6500 rpm' '177 bhp @ 4500 rpm' '335 bhp @ 6500 rpm'
 '245 bhp @ 5500 rpm' '68 bhp @ 3600 rpm' '147 bhp @ 3400 rpm' '272@6000'
 '64@6200' '218@4000' '217 bhp @ 4400 rpm' '265 bhp @ 4000 rpm'
 '87 bhp @ 3800 rpm' '46 bhp @ 6200 rpm' '132@6000' '241 bhp @ 5000 rpm'
 '235 bhp @ 4250 rpm' '168 bhp @ 3500 rpm' '162 bhp @ 4000 rpm' '100@5500'
 '71 bhp @ 6250 rpm' '75 bhp @ 4000 rpm' '241 bhp @ 4000 rpm'
 '570 bhp @ 5250 rpm' '89 bhp @ 4200 rpm' '194 bhp @ 3800 rpm'
 '194 bhp @ 5700 rpm' '114 bhp @ 5000 rpm' '195 bhp @ 4000 rpm' '105@3800'
 '396 bhp @ 6500 rpm' '39 bhp @ 6200 rpm' '158 bhp @ 4500 rpm'
 '165 bhp @ 3500 rpm' '349 bhp @ 5400 rpm' '150 bhp @ 6200 rpm'
 '94 bhp @ 5500 rpm' '176 bhp @ 5700 rpm' '189 bhp @ 4400 rpm'
 '72 bhp @ 6000 rpm' '106 bhp @ 6000 rpm' '237 bhp @ 4000 rpm' '68@4000'
 '115 bhp @ 4700 rpm' '271 bhp @ 4000 rpm' '335 bhp @ 5000 rpm'
 '260 bhp @ 4000 rpm' '161 bhp @ 5500 rpm' '335 bhp @ 5500 rpm'
 '141 bhp @ 4200 rpm' '90@4000' '158 bhp @ 3200 rpm' '69@4000'
 '121 bhp @ 6400 rpm' '67@5500' '225 bhp @ 4000 rpm' '48 bhp @ 6000 rpm'
 '247 bhp @ 4000 rpm' '98 bhp @ 3600 rpm' '178 bhp @ 4000 rpm'
 '197 bhp @ 3800 rpm' '168 bhp @ 3400 rpm' '137 bhp @ 3750 rpm'
 '121 bhp @ 5000 rpm' '385 bhp @ 5500 rpm' '188 bhp @ 3800 rpm'
 '190 bhp @ 4200 rpm' '63 bhp @ 4000 rpm' '187 bhp @ 4250 rpm'
 '109 bhp @ 4000 rpm' '102@5500' '240@4000' '79 bhp @ 5600 rpm'
 '63 bhp @ 3200 rpm' '58 bhp @ 4000 rpm' '187 bhp @ 5000 rpm'
 '178 bhp @ 6500 rpm' '73 bhp @ 4000 rpm' '268 bhp @ 5150 rpm'
 '110 bhp @ 6300 rpm' '227 bhp @ 5500 rpm' '161 bhp @ 4200 rpm'
 '67.7 bhp @ 6200 rpm' '190 bhp @ 4250 rpm' '228 bhp @ 5200 rpm'
 '232 bhp @ 4250 rpm' '46 bhp @ 3500 rpm' '58@6000' '235 bhp @ 4000 rpm'
 '261 bhp @ 4000 rpm' '362 bhp @ 5250 rpm' '62 bhp @ 5400 rpm'
 '154 bhp @ 6500 rpm' '120 bhp @ 5000 rpm' '78@5500' '77 bhp @ 3750 rpm'
 '98 bhp @ 6000 rpm' '236 bhp @ 5500 rpm' '198@4000' '247 bhp @ 5500 rpm'
 '197 bhp @ 5000 rpm' '70 bhp @ 4000 rpm' '329 bhp @ 5250 rpm']

col_name : Max Torque
compo : ['109 Nm @ 4500 rpm' '190 Nm @ 2000 rpm' '112.7619 Nm @ 4000 rpm'
 '113 Nm @ 4200 rpm' '343 Nm @ 1400 rpm' '130 Nm @ 4000 rpm'
 '300 Nm @ 1200 rpm' '400 Nm @ 1750 rpm' '250 Nm @ 1250 rpm'
 '200 Nm @ 1900 rpm' '115 Nm @ 4000 rpm' '91 Nm @ 4250 rpm'
 '138 Nm @ 4400 rpm' '350 Nm @ 1750 rpm' '175 Nm @ 1500 rpm'
 '90 Nm @ 3500 rpm' '69 Nm @ 3500 rpm' '154 Nm @ 4850 rpm'
 '153 Nm @ 3800 rpm' '99 Nm @ 4500 rpm' '172 Nm @ 1500 rpm'
 '78 Nm @ 3500 rpm' '113 Nm @ 4500 rpm' '110 Nm @ 4800 rpm'
 '265 Nm @ 1900 rpm' '170 Nm @ 1400 rpm' nan '96 Nm @ 3000 rpm'
 '114 Nm @ 3500 rpm' '140 Nm @ 1800 rpm' '400 Nm @ 1400 rpm'
 '260 Nm @ 1500 rpm' '500 Nm @ 1600 rpm' '173 Nm @ 4000 rpm'
 '380 Nm @ 1750 rpm' '240@3000' '247 Nm @ 1800 rpm' '200 Nm @ 1750 rpm'
 '200 Nm @ 1200 rpm' '290 Nm @ 1800 rpm' '270 Nm @ 1350 rpm'
 '145 Nm @ 4600 rpm' '180 Nm @ 2000 rpm' '101 Nm @ 3000 rpm'
 '112 Nm @ 4000 rpm' '450 Nm @ 1600 rpm' '171.62 Nm @ 4300 rpm'
 '113 Nm @ 4400 rpm' '240 Nm @ 1500 rpm' '320 Nm @ 1750 rpm'
 '160 Nm @ 2000 rpm' '110 Nm @ 3750 rpm' '233 Nm @ 4100 rpm'
 '320 Nm @ 1500 rpm' '500@1600' '400 Nm @ 2800 rpm' '270 Nm @ 4500 rpm'
 '248 Nm @ 2250 rpm' '77 Nm @ 3500 rpm' '560 Nm @ 1500 rpm'
 '450 Nm @ 1340 rpm' '370 Nm @ 1300 rpm' '158 Nm @ 4200 rpm'
 '300 Nm @ 1500 rpm' '300 Nm @ 1250 rpm' '146@4600' '360 Nm @ 1400 rpm'
 '190 Nm @ 1750 rpm' '89@3000' '114 Nm @ 4000 rpm' '242 Nm @ 1500 rpm'
 '600 Nm @ 1500 rpm' '260 Nm @ 1900 rpm' '277@1700' '370 Nm @ 1600 rpm'
 '142 Nm @ 4000 rpm' '151 Nm @ 4850 rpm' '113.796 Nm @ 4000 rpm'
 '300 Nm @ 1750 rpm' '250 Nm @ 1500 rpm' '400 Nm @ 1600 rpm'
 '430 Nm @ 1750 rpm' '700 Nm @ 1800 rpm' '250 Nm @ 1600 rpm'
 '144 Nm @ 4400 rpm' '215@3600' '220 Nm @ 1500 rpm' '360 Nm @ 1750 rpm'
 '300 Nm @ 1600 rpm' '90@3500' '205 Nm @ 1750 rpm' '550 Nm @ 1750 rpm'
 '280 Nm @ 1800 rpm' '190@2000' '200@1400' '535@1600' '350 Nm @ 1500 rpm'
 '285 Nm @ 4000 rpm' '540@1600' '619 Nm @ 1600 rpm'
 '219.744 Nm @ 1500 rpm' '175 Nm @ 1750 rpm' '170 Nm @ 1750 rpm'
 '153 Nm @ 3750 rpm' '430 Nm @ 4000 rpm' '350 Nm @ 5000 rpm'
 '72 Nm @ 4386 rpm' '360 Nm @ 1200 rpm' '600 Nm @ 2000 rpm'
 '700 Nm @ 2250 rpm' '343@1400' '520 Nm @ 2000 rpm' '330 Nm @ 2800 rpm'
 '113 Nm @ 3300 rpm' '400 Nm @ 1500 rpm' '84@3500' '330 Nm @ 1600 rpm'
 '550 Nm @ 2750 rpm' '400@2000' '380 Nm @ 1800 rpm' '320 Nm @ 1700 rpm'
 '111@4000' '620 Nm @ 1600 rpm' '190@3000' '62@3000' '390 Nm @ 5600 rpm'
 '192 Nm @ 4000 rpm' '113 Nm @ 4000 rpm' '600 Nm @ 1600 rpm'
 '420 Nm @ 1750 rpm' '220@1400' '250 Nm @ 2500 rpm' '204 Nm @ 2000 rpm'
 '350 Nm @ 1450 rpm' '620 Nm @ 1500 rpm' '177 Nm @ 4700 rpm' '113@4500'
 '115@4500' '145 Nm @ 4300 rpm' '245 Nm @ 4000 rpm' '350 Nm @ 1600 rpm'
 '280 Nm @ 1600 rpm' '95 Nm @ 4000 rpm' '250@1500' '182@4000'
 '170 Nm @ 1800 rpm' '152 Nm @ 2200 rpm' '94 Nm @ 3500 rpm'
 '345 Nm @ 4500 rpm' '144 Nm @ 4500 rpm' '102 Nm @ 4000 rpm' '245@5000'
 '700 Nm @ 2000 rpm' '320 Nm @ 1600 rpm' '300 Nm @ 1400 rpm'
 '160 Nm @ 1500 rpm' '77@3500' '400 Nm @ 1700 rpm' '270 Nm @ 1750 rpm'
 '200 Nm @ 1400 rpm' '116@4750' '215 Nm @ 1750 rpm' '380 Nm @ 1950 rpm'
 '155 Nm @ 4200 rpm' '170@3500' '240 Nm @ 1600 rpm' '760 Nm @ 3000 rpm'
 '340 Nm @ 1750 rpm' '48@3000' '400 Nm @ 2000 rpm' '470 Nm @ 1750 rpm'
 '104 Nm @ 4000 rpm' '560 Nm @ 6500 rpm' '115 Nm @ 4200 rpm'
 '75 Nm @ 4000 rpm' '620 Nm @ 2000 rpm' '380 Nm @ 2500 rpm'
 '132 Nm @ 3000 rpm' '95 Nm @ 3000 rpm' '140 Nm @ 4400 rpm'
 '700 Nm @ 1200 rpm' '146 Nm @ 4800 rpm' '290@1800' '480 Nm @ 1500 rpm'
 '230 Nm @ 1500 rpm' '505 Nm @ 4400 rpm' '240 Nm @ 1850 rpm'
 '420 Nm @ 1600 rpm' '320 Nm @ 1650 rpm' '75@4000' '450 Nm @ 1750 rpm'
 '115 Nm @ 1500 rpm' '343 @1400' '500 Nm @ 1370 rpm' '280 Nm @ 1350 rpm'
 '104 Nm @ 4400 rpm' '191 Nm @ 4500 rpm' '320 Nm @ 1400 rpm'
 '380 Nm @ 2000 rpm' '323@2000' '160 Nm @ 1750 rpm' '225 Nm @ 1500 rpm'
 '224 Nm @ 1500 rpm' '99.081 Nm @ 4500 rpm' '195 Nm @ 1400 rpm'
 '250 Nm @ 150 rpm' '292 Nm @ 2000 rpm' '500 Nm @ 1400 rpm' '327@2600'
 '280 Nm @ 1250 rpm' '410@2000' '200 Nm @ 2000 rpm' '150 Nm @ 4500 rpm'
 '380 Nm @ 2150 rpm' '450 Nm @ 3500 rpm' '110 Nm @ 4000 rpm'
 '365 Nm @ 1500 rpm' '170 Nm @ 2400 rpm' '350@2400' '402 Nm @ 3000 rpm'
 '480@1750' '259 Nm @ 1900 rpm' '320 Nm @ 1450 rpm' '450 Nm @ 1500 rpm'
 '205 Nm @ 1800 rpm' '85 Nm @ 3500 rpm' '170@4200' '350@1750'
 '480 Nm @ 1750 rpm' '420 Nm @ 2000 rpm' '340 Nm @ 3250 rpm'
 '99.08 Nm @ 4500 rpm' '137@4200' '96 Nm @ 3500 rpm' '197 Nm @ 1750 rpm'
 '780 Nm @ 1500 rpm' '437 Nm @ 1800 rpm' '210 Nm @ 4200 rpm'
 '178 Nm @ 1750 rpm' '436 Nm @ 1800 rpm' '247@1800' '515 Nm @ 4250 rpm'
 '54 Nm @ 3000 rpm' '400 Nm @ 2750 rpm' '480 Nm @ 1360 rpm' '112@4000'
 '125 Nm @ 3500 rpm' '221 Nm @ 3600 rpm' '98 Nm @ 3000 rpm'
 '140 Nm @ 4200 rpm' '430 Nm @ 1400 rpm' '160@2000' '198 Nm @ 2800 rpm'
 '220@1750' '350 Nm @ 1800 rpm' '385 Nm @ 1600 rpm' '84 Nm @ 4500 rpm'
 '99@2800' '213 Nm @ 4500 rpm' '689 Nm @ 1800 rpm' '580 Nm @ 1750 rpm'
 '320@2000' '440 Nm @ 1750 rpm' '350 Nm @ 1400 rpm' '319 Nm @ 1500 rpm'
 '200 Nm @ 1250 rpm' '520 Nm @ 2500 rpm' '180 Nm @ 1750 rpm' '145@4200'
 '500@1500' '104 Nm @ 3100 rpm' '150 Nm @ 1750 rpm' '300 Nm @ 1300 rpm'
 '222 Nm @ 4300 rpm' '250 Nm @ 1620 rpm' '400 Nm @ 3000 rpm'
 '350 Nm @ 1250 rpm' '380 Nm @ 1200 rpm' '440 Nm @ 1500 rpm'
 '125 Nm @ 2000 rpm' '77@4500' '490 Nm @ 1800 rpm' '200@3400'
 '500 Nm @ 1800 rpm' '90 Nm @ 4200 rpm' '190 Nm @ 4300 rpm' '125@2700'
 '134 Nm @ 4000 rpm' '456@1400' '113 Nm @ 5000 rpm' '480 Nm @ 1600 rpm']

col_name : Drivetrain
compo : ['FWD' 'RWD' 'AWD' nan]

범주형 자료들을 출력해보았다. 이런 범주형 변수들까지 학습시키기 위해선, 추후 **LabelEncoder를 이용하여 각 고유한 값들을 전부 0과 1의 고유벡터로 전환시켜야 할 것**이다.